apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sprolo
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/sprolo/sprolo-app:latest
          ports:
            - name: http1
              containerPort: 3000
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: NODE_ENV
              value: "production"
__ENV_BLOCK__
